name: Deploy ASP.NET Core to Azure Web App

env:
  AZURE_WEBAPP_NAME: frontfondos      # Nombre exacto de tu Web App en Azure
  DOTNET_VERSION: '8.0'               # Versi칩n de .NET (coincide con tu runtime stack)
  PUBLISH_OUTPUT: 'publish'           # Carpeta donde se guardar치n los archivos publicados

on:
  push:
    branches: [ "main" ]              # Dispara el workflow en pushes a main
  workflow_dispatch:                  # Permite ejecuciones manuales

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production           # Opcional: Define un entorno (aparece en GitHub)

    steps:
      # Paso 1: Checkout del c칩digo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar .NET
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Paso 3: Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore cliente.API/cliente.API.csproj

      # Paso 4: Compilar en modo Release
      - name: Build
        run: dotnet build ElCliente.API/ElCliente.API.csproj --configuration Release --no-restore

      # Paso 5: Publicar la aplicaci칩n
      - name: Publish
        run: dotnet publish ElCliente.API/ElCliente.API.csproj -c Release -o ${{ github.workspace }}/${{ env.PUBLISH_OUTPUT }}

      # Paso 6: Desplegar en Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/${{ env.PUBLISH_OUTPUT }}
